parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: appsell
        connections:
            appsell:
                driver: 'pdo_pgsql'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                url: '%env(DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: appsell
        entity_managers:
            appsell:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                connection: appsell
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
