nelmio_cors:
  defaults:
    origin_regex: true
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    allow_headers: ['Content-Type', 'Authorization']
    max_age: 3600
    allow_origin:
      - '^https?://localhost'
      - '^https?://appsell.me'
  paths:
    '^/': ~
