security:

    role_hierarchy:

        ROLE_ADMIN:
            - ROLE_OWNER
            - ROLE_SELLER
            - ROLE_EMPLOYEE

            - ROLE_USER
            - ROLE_ALLOWED_TO_SWITCH

            - ROLE_APP_USER_PROFILE

            - ROLE_APP_OFFER_EDIT
            - ROLE_APP_OFFER_LIST
            - ROLE_APP_OFFER_CREATE
            - ROLE_APP_OFFER_DELETE
            - ROLE_APP_OFFER_CHANGE_ACTIVITY      # изменение активности оффера
            - ROLE_APP_OFFER_CHANGE_ACCESSIBILITY # изменение видимости оффера для сотрудников
            - ROLE_APP_OFFER_HIDE                 # скрытие из списка ака "удаление" для заказчика
            - ROLE_APP_OFFER_CHANGE_COMMISSION    # изменение комиссии для оффера

            - ROLE_APP_USER_CHANGE_COMMISSION     # изменение комиссии для пользователя

            - ROLE_APP_EVENT_TYPE_EDIT
            - ROLE_APP_EVENT_TYPE_LIST
            - ROLE_APP_EVENT_TYPE_CREATE
            - ROLE_APP_EVENT_TYPE_DELETE

            - ROLE_APP_NOTIFICATION_LIST
            - ROLE_APP_NOTIFICATION_CREATE
            - ROLE_APP_NOTIFICATION_DELETE

            - ROLE_APP_STAT_LIST

            - ROLE_APP_REPORT_LIST

            - ROLE_IMPORT_CSV_LIST
            - ROLE_IMPORT_CSV_IMPORT

            - ROLE_FOLLOWED_USER_LIST              # Просмотр статистики о приведенных пользователем других пользователей

            - ROLE_PAYOUT_LIST                     # Просмотр списка транзакций выплат
            - ROLE_PAYOUT_APPROVE                  # Отправка транзакции на вывод в SolarStaff

            - ROLE_CLICK_STATS_LIST                # Отчет по исполнению офферов (по умолчанию, видно своих сотрудников)
            - ROLE_CLICK_STATS_LIST_ALL            # Отчет по исполнению офферов любыми акаунтами (видит все)

        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN

            - ROLE_APP_COMMISSION_EDIT
            - ROLE_APP_COMMISSION_LIST
            - ROLE_APP_COMMISSION_CREATE
            - ROLE_APP_COMMISSION_DELETE

            - ROLE_APP_USER_EDIT
            - ROLE_APP_USER_LIST
            - ROLE_APP_USER_CREATE
            - ROLE_APP_USER_DELETE

            - ROLE_APP_GROUP_EDIT
            - ROLE_APP_GROUP_LIST
            - ROLE_APP_GROUP_CREATE
            - ROLE_APP_GROUP_DELETE

            - ROLE_APP_USER_PROFILE_EDIT
            - ROLE_APP_USER_PROFILE_LIST
            - ROLE_APP_USER_PROFILE_CREATE
            - ROLE_APP_USER_PROFILE_DELETE