security:

    role_hierarchy:

        ROLE_ADMIN:
            - ROLE_OWNER
            - ROLE_SELLER
            - ROLE_EMPLOYEE

            - ROLE_USER
            - ROLE_ALLOWED_TO_SWITCH

            - ROLE_APP_USER_PROFILE

            - ROLE_APP_OFFER_EDIT
            - ROLE_APP_OFFER_LIST
            - ROLE_APP_OFFER_CREATE
            - ROLE_APP_OFFER_DELETE
            - ROLE_APP_OFFER_CHANGE_ACTIVITY      # изменение активности оффера
            - ROLE_APP_OFFER_CHANGE_ACCESSIBILITY # изменение видимости оффера для сотрудников
            - ROLE_APP_OFFER_HIDE                 # скрытие из списка ака "удаление" для заказчика
            - ROLE_APP_OFFER_CHANGE_COMMISSION    # изменение комиссии для оффера

            - ROLE_APP_USER_CHANGE_COMMISSION     # изменение комиссии для пользователя

            - ROLE_APP_EVENT_TYPE_EDIT
            - ROLE_APP_EVENT_TYPE_LIST
            - ROLE_APP_EVENT_TYPE_CREATE
            - ROLE_APP_EVENT_TYPE_DELETE

            - ROLE_APP_STAT_LIST
            - ROLE_APP_STAT_CREATE
            - ROLE_APP_STAT_DELETE

        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN

            - ROLE_APP_COMMISSION_EDIT
            - ROLE_APP_COMMISSION_LIST
            - ROLE_APP_COMMISSION_CREATE
            - ROLE_APP_COMMISSION_DELETE

            - ROLE_APP_USER_EDIT
            - ROLE_APP_USER_LIST
            - ROLE_APP_USER_CREATE
            - ROLE_APP_USER_DELETE

            - ROLE_APP_GROUP_EDIT
            - ROLE_APP_GROUP_LIST
            - ROLE_APP_GROUP_CREATE
            - ROLE_APP_GROUP_DELETE

            - ROLE_APP_USER_PROFILE_EDIT
            - ROLE_APP_USER_PROFILE_LIST
            - ROLE_APP_USER_PROFILE_CREATE
            - ROLE_APP_USER_PROFILE_DELETE