security:

    role_hierarchy:

        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_SONATA_ADMIN
            - ROLE_ALLOWED_TO_SWITCH

            - ROLE_APP_SONATA_ADMIN_USER_EDIT
            - ROLE_APP_SONATA_ADMIN_USER_LIST
            - ROLE_APP_SONATA_ADMIN_USER_CREATE
            - ROLE_APP_SONATA_ADMIN_USER_VIEW
            - ROLE_APP_SONATA_ADMIN_USER_DELETE
            - ROLE_APP_SONATA_ADMIN_USER_EXPORT
            - ROLE_APP_SONATA_ADMIN_USER_ALL

            - ROLE_APP_SONATA_ADMIN_USER_PROFILE_EDIT
            - ROLE_APP_SONATA_ADMIN_USER_PROFILE_LIST
            - ROLE_APP_SONATA_ADMIN_USER_PROFILE_CREATE
            - ROLE_APP_SONATA_ADMIN_USER_PROFILE_VIEW
            - ROLE_APP_SONATA_ADMIN_USER_PROFILE_DELETE
            - ROLE_APP_SONATA_ADMIN_USER_PROFILE_EXPORT
            - ROLE_APP_SONATA_ADMIN_USER_PROFILE_ALL

            - ROLE_APP_SONATA_ADMIN_GROUP_EDIT
            - ROLE_APP_SONATA_ADMIN_GROUP_LIST
            - ROLE_APP_SONATA_ADMIN_GROUP_CREATE
            - ROLE_APP_SONATA_ADMIN_GROUP_VIEW
            - ROLE_APP_SONATA_ADMIN_GROUP_DELETE
            - ROLE_APP_SONATA_ADMIN_GROUP_EXPORT
            - ROLE_APP_SONATA_ADMIN_GROUP_ALL

        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN