version: '3'
services:

  php-fpm:
    container_name: appsell_php_fpm
    image: appsell_php_fpm
    build:
      context: .
      dockerfile: ./build/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/app
      - ./var:/var/www/app/var
    ports:
      - 9000

  nginx:
    container_name: appsell_nginx
    image: appsell_nginx
    build: ./build/nginx
    links:
      - php-fpm
    ports:
      - 80:80
    volumes:
      - ./:/var/www/app
      - ./var:/var/www/app/var
