version: '3'
services:

  swagger-ui:
    container_name: appsell_swagger_ui
    image: swaggerapi/swagger-ui
    environment:
      API_URL: http://localhost/api/swagger

  php-fpm:
    container_name: appsell_php_fpm
    image: appsell_php_fpm
    build:
      context: .
      dockerfile: ./build/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/app
      - ./var:/var/www/app/var
    ports:
      - 9000
    environment:
      - APP_ENV=dev
      - APP_LOCALE=ru
      - APP_SECRET=86e7b44293d50666286e7b44293d5066620c4381b619a9cfea7bf5ec20c4381b619a9cfea7bf5ec2
      - DATABASE_URL=pgsql://backend:Wq2v9LV4UP@10.1.4.5:5432/appsell
      - MAILER_URL=gmail://appsell@sixdays.ru:%H$$b2Bp2[vMcPL5@smtp.gmail.com:465?encryption=ssl

  nginx:
    container_name: appsell_nginx
    image: appsell_nginx
    build:
      context: .
      dockerfile: ./build/nginx/Dockerfile
    links:
      - php-fpm
      - swagger-ui
    ports:
      - 80:80
    volumes:
      - ./:/var/www/app
      - ./var:/var/www/app/var
