version: '3'
services:

  php-fpm:
    container_name: appsell_php_fpm
    image: appsell_php_fpm
    build:
      context: .
      dockerfile: ./build/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/app
      - ./var:/var/www/app/var
    ports:
      - 9000
    environment:
      - APP_ENV=dev
      - APP_LOCALE=ru
      - APP_SECRET=86e7b44293d50666286e7b44293d5066620c4381b619a9cfea7bf5ec20c4381b619a9cfea7bf5ec2
      - CORS_ALLOW_ORIGIN=^https?://localhost:?[0-9]*$$
      - DATABASE_URL=pgsql://backend:Wq2v9LV4UP@10.1.4.5:5432/appsell

  nginx:
    container_name: appsell_nginx
    image: appsell_nginx
    build:
      context: .
      dockerfile: ./build/nginx/Dockerfile
    links:
      - php-fpm
    ports:
      - 80:80
    volumes:
      - ./:/var/www/app
      - ./var:/var/www/app/var
