---

- hosts: all
  become_user: root

  vars:
    registry_host: 11.1.1.5
    registry_port: 5000

  tasks:

    - name: app - nginx
      docker_container:
        pull: yes
        name: appsell_frontend_nginx
        image: "{{ registry_host }}:{{ registry_port }}/frontend/nginx"
        state: started
        restart_policy: unless-stopped
        recreate: yes
        ports:
          - 8002:80
        #dns_servers: ["{{ ansible_docker0.ipv4.address }}"]