# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

  access_token.secret:            'e2374ce25abcd4342ed59f24fd3d317bb01a9e01'
  access_token.expires_in:        2592000 # 30 дней
  system.notification_receivers:  ['andrey@sixdays.ru'] # Получатель уведомлений от системы

  # Данные для доступа к API solar-staff.com
  solar_staff.api_url:       '%env(SOLAR_STAFF_API_URL)%'
  solar_staff.api_client_id: '%env(SOLAR_STAFF_API_CLIENT_ID)%'
  solar_staff.api_salt:      '%env(SOLAR_STAFF_API_SALT)%'
  solar_staff.oferta_url:    'https://www.solar-staff.com/docs/ofertafreelancer.pdf'
  solar_staff.login_url:     '%env(SOLAR_STAFF_LOGIN_URL)%'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false       # Allows optimizing the container by removing unused services; this also means
                        # fetching services directly from the container via $container->get() won't work.
                        # The best practice is to be explicit about your dependencies anyway.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude: '../src/{Lib,Entity,Migrations,Tests,Swagger,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  App\Service\:
    resource: '../src/Service'
    public: true

  App\Security\AccessToken:
    arguments:
      - '%access_token.secret%'
      - '%access_token.expires_in%'

  App\Notification\Producer\SystemProducer:
    arguments:
      - '@App\Notification\Notificator\EmailNotificator'
      - '%system.notification_receivers%'

  App\SolarStaff\Transport:
    arguments:
      - '%solar_staff.api_url%'
      - '%solar_staff.api_client_id%'
      - '%solar_staff.api_salt%'

  App\SolarStaff\Client:
    arguments:
      - '@App\SolarStaff\Transport'
      - '%solar_staff.login_url%'
      - '%solar_staff.oferta_url%'

  # rabbitmq processors

  queue.processor:
    class: App\Queue\Processor\Processor
    public: true
