---

- hosts: all

  tasks:

    - name: Остановка контейнеров
      docker_container:
        name: "{{ item }}"
        state: absent
      with_items:
        - appsell_backend_nginx
        - appsell_backend_fpm
        - appsell_backend_swagger_ui
