---

- hosts: all
  become_user: root

  vars:
    registry_host: 11.1.1.5
    registry_port: 5000
    var_dir: /datadrive/app/backend/var
    app_env: dev
    app_locale: "ru"
    app_secret: "86e7b44293d50666286e7b44293d5066620c4381b619a9cfea7bf5ec20c4381b619a9cfea7bf5ec2"
    database_url: "pgsql://backend:Wq2v9LV4UP@11.1.1.5:5432/appsell"
    mailer_url: "gmail://appsell@sixdays.ru:%H$b2Bp2[vMcPL5@smtp.gmail.com:465?encryption=ssl"
    cors_allow_origin: "^https?://localhost:?[0-9]*$"
    rabbitmq_dsn: "amqp://admin:c58znNLBxWqzuT5@11.1.1.5:5672/appsell"
    firebase_api_key: "AAAAwxBBPL4:APA91bFVrKfPUiCGFpO942f0DlaIEevXADVujey_O7yTmaRE80G-GBl7c1Zj_UJzISRm8LOJ2asJBtD0e4AIoG2MlGsFX47luVtRW2fJv0Az0n7k16weHGLTW_ITt7vHr_QAmQAXQ3sBuTiDkrvOYQ74GCGUCMfGjw"
    solar_staff_api_url: "https://test.solar-api.com"
    solar_staff_api_client_id: "435"
    solar_staff_api_salt: "8e2a9b046a23d563a93aaf"
    solar_staff_login_url: "https://test.solar-staff.com/#login"

  tasks:
    - import_tasks: "_up.yml"